spring:
  application:
      name: career-security
  cloud:
    bootstrap:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:25432/career
    username: career
    password: sql
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
