spring:
  application:
      name: career-security
  cloud:
    bootstrap:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:25432/career
    username: career
    password: sql
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
security:
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
